#!/usr/bin/env bash
set -eufo pipefail

npm outdated --long
npm whoami
npm run build
npm run build:dist
sed --in-place "s/Fluture@$PREVIOUS_VERSION/Fluture@$VERSION/" README.md
git add dist README.md
