#!/usr/bin/env bash
set -euxo pipefail

npm run build
./node_modules/.bin/rollup -c rollup.config.dist.js
sed --in-place "s/Fluture@$PREVIOUS_VERSION/Fluture@$VERSION/" README.md
git add dist README.md
